# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 420)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.portLineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLineEdit.sizePolicy().hasHeightForWidth())
        self.portLineEdit.setSizePolicy(sizePolicy)
        self.portLineEdit.setMaximumSize(QtCore.QSize(140, 16777215))
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout.addWidget(self.portLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.connectPushButton = QtWidgets.QPushButton(self.widget)
        self.connectPushButton.setObjectName("connectPushButton")
        self.horizontalLayout.addWidget(self.connectPushButton)
        self.verticalLayout.addWidget(self.widget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.ledColorWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledColorWidget.sizePolicy().hasHeightForWidth())
        self.ledColorWidget.setSizePolicy(sizePolicy)
        self.ledColorWidget.setObjectName("ledColorWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ledColorWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LED0RadioButton = QtWidgets.QRadioButton(self.ledColorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED0RadioButton.sizePolicy().hasHeightForWidth())
        self.LED0RadioButton.setSizePolicy(sizePolicy)
        self.LED0RadioButton.setObjectName("LED0RadioButton")
        self.horizontalLayout_2.addWidget(self.LED0RadioButton)
        self.LED1RadioButton = QtWidgets.QRadioButton(self.ledColorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED1RadioButton.sizePolicy().hasHeightForWidth())
        self.LED1RadioButton.setSizePolicy(sizePolicy)
        self.LED1RadioButton.setObjectName("LED1RadioButton")
        self.horizontalLayout_2.addWidget(self.LED1RadioButton)
        self.LED2RadioButton = QtWidgets.QRadioButton(self.ledColorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED2RadioButton.sizePolicy().hasHeightForWidth())
        self.LED2RadioButton.setSizePolicy(sizePolicy)
        self.LED2RadioButton.setObjectName("LED2RadioButton")
        self.horizontalLayout_2.addWidget(self.LED2RadioButton)
        self.LED3RadioButton = QtWidgets.QRadioButton(self.ledColorWidget)
        self.LED3RadioButton.setObjectName("LED3RadioButton")
        self.horizontalLayout_2.addWidget(self.LED3RadioButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.ledColorWidget)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget = ColorimeterTableWidget(self.frame)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.frame)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.samplesLabel = QtWidgets.QLabel(self.widget_3)
        self.samplesLabel.setObjectName("samplesLabel")
        self.horizontalLayout_3.addWidget(self.samplesLabel)
        self.samplesLineEdit = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.samplesLineEdit.sizePolicy().hasHeightForWidth())
        self.samplesLineEdit.setSizePolicy(sizePolicy)
        self.samplesLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.samplesLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.samplesLineEdit.setObjectName("samplesLineEdit")
        self.horizontalLayout_3.addWidget(self.samplesLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.calibratePushButton = QtWidgets.QPushButton(self.widget_3)
        self.calibratePushButton.setObjectName("calibratePushButton")
        self.horizontalLayout_3.addWidget(self.calibratePushButton)
        self.clearPushButton = QtWidgets.QPushButton(self.widget_3)
        self.clearPushButton.setObjectName("clearPushButton")
        self.horizontalLayout_3.addWidget(self.clearPushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.measurePushButton = QtWidgets.QPushButton(self.widget_3)
        self.measurePushButton.setObjectName("measurePushButton")
        self.horizontalLayout_3.addWidget(self.measurePushButton)
        self.plotPushButton = QtWidgets.QPushButton(self.widget_3)
        self.plotPushButton.setObjectName("plotPushButton")
        self.horizontalLayout_3.addWidget(self.plotPushButton)
        self.verticalLayout.addWidget(self.widget_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuFitType = QtWidgets.QMenu(self.menuOptions)
        self.menuFitType.setObjectName("menuFitType")
        self.menuUnits = QtWidgets.QMenu(self.menuOptions)
        self.menuUnits.setObjectName("menuUnits")
        self.menuSignificantDigits = QtWidgets.QMenu(self.menuOptions)
        self.menuSignificantDigits.setObjectName("menuSignificantDigits")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionEditTestSolutions = QtWidgets.QAction(MainWindow)
        self.actionEditTestSolutions.setObjectName("actionEditTestSolutions")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFitTypeLinear = QtWidgets.QAction(MainWindow)
        self.actionFitTypeLinear.setCheckable(True)
        self.actionFitTypeLinear.setObjectName("actionFitTypeLinear")
        self.actionFitTypePolynomial2 = QtWidgets.QAction(MainWindow)
        self.actionFitTypePolynomial2.setCheckable(True)
        self.actionFitTypePolynomial2.setObjectName("actionFitTypePolynomial2")
        self.actionUnitsUM = QtWidgets.QAction(MainWindow)
        self.actionUnitsUM.setCheckable(True)
        self.actionUnitsUM.setObjectName("actionUnitsUM")
        self.actionUnitsPPM = QtWidgets.QAction(MainWindow)
        self.actionUnitsPPM.setCheckable(True)
        self.actionUnitsPPM.setObjectName("actionUnitsPPM")
        self.actionFitTypePolynomial3 = QtWidgets.QAction(MainWindow)
        self.actionFitTypePolynomial3.setCheckable(True)
        self.actionFitTypePolynomial3.setObjectName("actionFitTypePolynomial3")
        self.actionFitTypePolynomial4 = QtWidgets.QAction(MainWindow)
        self.actionFitTypePolynomial4.setCheckable(True)
        self.actionFitTypePolynomial4.setObjectName("actionFitTypePolynomial4")
        self.actionFitTypePolynomial5 = QtWidgets.QAction(MainWindow)
        self.actionFitTypePolynomial5.setCheckable(True)
        self.actionFitTypePolynomial5.setObjectName("actionFitTypePolynomial5")
        self.actionStandardRGBLED = QtWidgets.QAction(MainWindow)
        self.actionStandardRGBLED.setCheckable(True)
        self.actionStandardRGBLED.setObjectName("actionStandardRGBLED")
        self.actionCustomLEDVerB = QtWidgets.QAction(MainWindow)
        self.actionCustomLEDVerB.setCheckable(True)
        self.actionCustomLEDVerB.setObjectName("actionCustomLEDVerB")
        self.actionSignificantDigits1 = QtWidgets.QAction(MainWindow)
        self.actionSignificantDigits1.setCheckable(True)
        self.actionSignificantDigits1.setObjectName("actionSignificantDigits1")
        self.actionSignificantDigits2 = QtWidgets.QAction(MainWindow)
        self.actionSignificantDigits2.setCheckable(True)
        self.actionSignificantDigits2.setObjectName("actionSignificantDigits2")
        self.actionSignificantDigits3 = QtWidgets.QAction(MainWindow)
        self.actionSignificantDigits3.setCheckable(True)
        self.actionSignificantDigits3.setObjectName("actionSignificantDigits3")
        self.actionSignificantDigits4 = QtWidgets.QAction(MainWindow)
        self.actionSignificantDigits4.setCheckable(True)
        self.actionSignificantDigits4.setObjectName("actionSignificantDigits4")
        self.actionCustomLEDVerC = QtWidgets.QAction(MainWindow)
        self.actionCustomLEDVerC.setCheckable(True)
        self.actionCustomLEDVerC.setObjectName("actionCustomLEDVerC")
        self.actionUnitsPH = QtWidgets.QAction(MainWindow)
        self.actionUnitsPH.setCheckable(True)
        self.actionUnitsPH.setObjectName("actionUnitsPH")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFitType.addAction(self.actionFitTypeLinear)
        self.menuFitType.addAction(self.actionFitTypePolynomial2)
        self.menuFitType.addAction(self.actionFitTypePolynomial3)
        self.menuFitType.addAction(self.actionFitTypePolynomial4)
        self.menuFitType.addAction(self.actionFitTypePolynomial5)
        self.menuUnits.addAction(self.actionUnitsUM)
        self.menuUnits.addAction(self.actionUnitsPPM)
        self.menuUnits.addAction(self.actionUnitsPH)
        self.menuOptions.addAction(self.actionExport)
        self.menuOptions.addAction(self.actionImport)
        self.menuOptions.addAction(self.actionEditTestSolutions)
        self.menuOptions.addAction(self.menuFitType.menuAction())
        self.menuOptions.addAction(self.menuUnits.menuAction())
        self.menuOptions.addAction(self.menuSignificantDigits.menuAction())
        self.menu_Help.addAction(self.actionAbout)
        self.menuMode.addAction(self.actionStandardRGBLED)
        self.menuMode.addAction(self.actionCustomLEDVerB)
        self.menuMode.addAction(self.actionCustomLEDVerC)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Colorimeter Plot"))
        self.label.setText(_translate("MainWindow", "Serial Port"))
        self.connectPushButton.setText(_translate("MainWindow", "Connect"))
        self.LED0RadioButton.setText(_translate("MainWindow", "LED0"))
        self.LED1RadioButton.setText(_translate("MainWindow", "LED1"))
        self.LED2RadioButton.setText(_translate("MainWindow", "LED2"))
        self.LED3RadioButton.setText(_translate("MainWindow", "LED3"))
        self.samplesLabel.setText(_translate("MainWindow", "Samples"))
        self.calibratePushButton.setText(_translate("MainWindow", "Calibrate"))
        self.clearPushButton.setText(_translate("MainWindow", "Clear"))
        self.measurePushButton.setText(_translate("MainWindow", "Measure"))
        self.plotPushButton.setText(_translate("MainWindow", "Plot"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuOptions.setTitle(_translate("MainWindow", "&Options"))
        self.menuFitType.setTitle(_translate("MainWindow", "Fit Type"))
        self.menuUnits.setTitle(_translate("MainWindow", "Units"))
        self.menuSignificantDigits.setTitle(_translate("MainWindow", "Significant Digits"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menuMode.setTitle(_translate("MainWindow", "&Mode"))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.action_About.setText(_translate("MainWindow", "About..."))
        self.actionLoad.setText(_translate("MainWindow", "Load..."))
        self.actionExport.setText(_translate("MainWindow", "Export Test Solution..."))
        self.actionImport.setText(_translate("MainWindow", "Import Test Solution..."))
        self.actionEditTestSolutions.setText(_translate("MainWindow", "Edit User Test Solutions..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionFitTypeLinear.setText(_translate("MainWindow", "Linear"))
        self.actionFitTypePolynomial2.setText(_translate("MainWindow", "Polynomial (order=2)"))
        self.actionUnitsUM.setText(_translate("MainWindow", "uM"))
        self.actionUnitsPPM.setText(_translate("MainWindow", "ppm"))
        self.actionFitTypePolynomial3.setText(_translate("MainWindow", "Polynomial (order=3)"))
        self.actionFitTypePolynomial4.setText(_translate("MainWindow", "Polynomial (order=4)"))
        self.actionFitTypePolynomial5.setText(_translate("MainWindow", "Polynomial (order=5)"))
        self.actionStandardRGBLED.setText(_translate("MainWindow", "Standard RGB LED"))
        self.actionCustomLEDVerB.setText(_translate("MainWindow", "One custom LED  (Ver. B)"))
        self.actionSignificantDigits1.setText(_translate("MainWindow", "1"))
        self.actionSignificantDigits2.setText(_translate("MainWindow", "2"))
        self.actionSignificantDigits3.setText(_translate("MainWindow", "3"))
        self.actionSignificantDigits4.setText(_translate("MainWindow", "4"))
        self.actionCustomLEDVerC.setText(_translate("MainWindow", "Two custom LEDs (Ver. C)"))
        self.actionUnitsPH.setText(_translate("MainWindow", "pH"))

from colorimeter.table_widget import ColorimeterTableWidget
