# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic.ui'
#
# Created: Mon Sep  2 17:32:39 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(682, 389)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtGui.QFrame(self.widget_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.transmissionGroupBox = QtGui.QGroupBox(self.frame)
        self.transmissionGroupBox.setObjectName("transmissionGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.transmissionGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.transmissionTextEdit = QtGui.QTextEdit(self.transmissionGroupBox)
        self.transmissionTextEdit.setReadOnly(True)
        self.transmissionTextEdit.setObjectName("transmissionTextEdit")
        self.verticalLayout.addWidget(self.transmissionTextEdit)
        self.verticalLayout_2.addWidget(self.transmissionGroupBox)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.widget_2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.absorbanceGroupBox = QtGui.QGroupBox(self.frame_2)
        self.absorbanceGroupBox.setObjectName("absorbanceGroupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.absorbanceGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.absorbanceTextEdit = QtGui.QTextEdit(self.absorbanceGroupBox)
        self.absorbanceTextEdit.setReadOnly(True)
        self.absorbanceTextEdit.setObjectName("absorbanceTextEdit")
        self.verticalLayout_3.addWidget(self.absorbanceTextEdit)
        self.verticalLayout_4.addWidget(self.absorbanceGroupBox)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.widget_5 = QtGui.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtGui.QLabel(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.samplesLineEdit = QtGui.QLineEdit(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.samplesLineEdit.sizePolicy().hasHeightForWidth())
        self.samplesLineEdit.setSizePolicy(sizePolicy)
        self.samplesLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.samplesLineEdit.setObjectName("samplesLineEdit")
        self.horizontalLayout_5.addWidget(self.samplesLineEdit)
        spacerItem = QtGui.QSpacerItem(143, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.LEDLabel = QtGui.QLabel(self.widget_5)
        self.LEDLabel.setObjectName("LEDLabel")
        self.horizontalLayout_5.addWidget(self.LEDLabel)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.LED0CheckBox = QtGui.QCheckBox(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED0CheckBox.sizePolicy().hasHeightForWidth())
        self.LED0CheckBox.setSizePolicy(sizePolicy)
        self.LED0CheckBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.LED0CheckBox.setChecked(True)
        self.LED0CheckBox.setObjectName("LED0CheckBox")
        self.horizontalLayout_5.addWidget(self.LED0CheckBox)
        self.LED1CheckBox = QtGui.QCheckBox(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED1CheckBox.sizePolicy().hasHeightForWidth())
        self.LED1CheckBox.setSizePolicy(sizePolicy)
        self.LED1CheckBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.LED1CheckBox.setChecked(True)
        self.LED1CheckBox.setObjectName("LED1CheckBox")
        self.horizontalLayout_5.addWidget(self.LED1CheckBox)
        self.LED2CheckBox = QtGui.QCheckBox(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED2CheckBox.sizePolicy().hasHeightForWidth())
        self.LED2CheckBox.setSizePolicy(sizePolicy)
        self.LED2CheckBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.LED2CheckBox.setChecked(True)
        self.LED2CheckBox.setObjectName("LED2CheckBox")
        self.horizontalLayout_5.addWidget(self.LED2CheckBox)
        self.LED3CheckBox = QtGui.QCheckBox(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED3CheckBox.sizePolicy().hasHeightForWidth())
        self.LED3CheckBox.setSizePolicy(sizePolicy)
        self.LED3CheckBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.LED3CheckBox.setChecked(True)
        self.LED3CheckBox.setObjectName("LED3CheckBox")
        self.horizontalLayout_5.addWidget(self.LED3CheckBox)
        self.verticalLayout_5.addWidget(self.widget_5)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.portLineEdit = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLineEdit.sizePolicy().hasHeightForWidth())
        self.portLineEdit.setSizePolicy(sizePolicy)
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout.addWidget(self.portLineEdit)
        self.connectPushButton = QtGui.QPushButton(self.widget)
        self.connectPushButton.setObjectName("connectPushButton")
        self.horizontalLayout.addWidget(self.connectPushButton)
        spacerItem2 = QtGui.QSpacerItem(322, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.calibratePushButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibratePushButton.sizePolicy().hasHeightForWidth())
        self.calibratePushButton.setSizePolicy(sizePolicy)
        self.calibratePushButton.setObjectName("calibratePushButton")
        self.horizontalLayout.addWidget(self.calibratePushButton)
        self.measurePushButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measurePushButton.sizePolicy().hasHeightForWidth())
        self.measurePushButton.setSizePolicy(sizePolicy)
        self.measurePushButton.setObjectName("measurePushButton")
        self.horizontalLayout.addWidget(self.measurePushButton)
        self.plotCheckBox = QtGui.QCheckBox(self.widget)
        self.plotCheckBox.setObjectName("plotCheckBox")
        self.horizontalLayout.addWidget(self.plotCheckBox)
        self.verticalLayout_5.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menuMode = QtGui.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        self.menu_Options = QtGui.QMenu(self.menubar)
        self.menu_Options.setObjectName("menu_Options")
        self.menuSignificantDigits = QtGui.QMenu(self.menu_Options)
        self.menuSignificantDigits.setObjectName("menuSignificantDigits")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionStandardRGBLED = QtGui.QAction(MainWindow)
        self.actionStandardRGBLED.setCheckable(True)
        self.actionStandardRGBLED.setObjectName("actionStandardRGBLED")
        self.actionCustomLEDVerB = QtGui.QAction(MainWindow)
        self.actionCustomLEDVerB.setCheckable(True)
        self.actionCustomLEDVerB.setObjectName("actionCustomLEDVerB")
        self.actionSignificantDigits1 = QtGui.QAction(MainWindow)
        self.actionSignificantDigits1.setCheckable(True)
        self.actionSignificantDigits1.setObjectName("actionSignificantDigits1")
        self.actionSignificantDigits2 = QtGui.QAction(MainWindow)
        self.actionSignificantDigits2.setCheckable(True)
        self.actionSignificantDigits2.setObjectName("actionSignificantDigits2")
        self.actionSignificantDigits3 = QtGui.QAction(MainWindow)
        self.actionSignificantDigits3.setCheckable(True)
        self.actionSignificantDigits3.setObjectName("actionSignificantDigits3")
        self.actionSignificantDigits4 = QtGui.QAction(MainWindow)
        self.actionSignificantDigits4.setCheckable(True)
        self.actionSignificantDigits4.setObjectName("actionSignificantDigits4")
        self.actionCustomLEDVerC = QtGui.QAction(MainWindow)
        self.actionCustomLEDVerC.setCheckable(True)
        self.actionCustomLEDVerC.setObjectName("actionCustomLEDVerC")
        self.menuFile.addAction(self.actionSave)
        self.menu_Help.addAction(self.actionAbout)
        self.menuMode.addAction(self.actionStandardRGBLED)
        self.menuMode.addAction(self.actionCustomLEDVerB)
        self.menuMode.addAction(self.actionCustomLEDVerC)
        self.menu_Options.addAction(self.menuSignificantDigits.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menu_Options.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Colorimeter Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.transmissionGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Transmittance", None, QtGui.QApplication.UnicodeUTF8))
        self.absorbanceGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Absorbance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Samples    ", None, QtGui.QApplication.UnicodeUTF8))
        self.LEDLabel.setText(QtGui.QApplication.translate("MainWindow", "LEDs", None, QtGui.QApplication.UnicodeUTF8))
        self.LED0CheckBox.setText(QtGui.QApplication.translate("MainWindow", "LED0", None, QtGui.QApplication.UnicodeUTF8))
        self.LED1CheckBox.setText(QtGui.QApplication.translate("MainWindow", "LED1", None, QtGui.QApplication.UnicodeUTF8))
        self.LED2CheckBox.setText(QtGui.QApplication.translate("MainWindow", "LED2", None, QtGui.QApplication.UnicodeUTF8))
        self.LED3CheckBox.setText(QtGui.QApplication.translate("MainWindow", "LED3", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Serial Port", None, QtGui.QApplication.UnicodeUTF8))
        self.connectPushButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.calibratePushButton.setText(QtGui.QApplication.translate("MainWindow", "Calibrate", None, QtGui.QApplication.UnicodeUTF8))
        self.measurePushButton.setText(QtGui.QApplication.translate("MainWindow", "Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.plotCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Plot   ", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMode.setTitle(QtGui.QApplication.translate("MainWindow", "&Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Options.setTitle(QtGui.QApplication.translate("MainWindow", "&Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSignificantDigits.setTitle(QtGui.QApplication.translate("MainWindow", "Significant Digits", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStandardRGBLED.setText(QtGui.QApplication.translate("MainWindow", "Standard RGB LED", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCustomLEDVerB.setText(QtGui.QApplication.translate("MainWindow", "LED Board B - single LED", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSignificantDigits1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSignificantDigits2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSignificantDigits3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSignificantDigits4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCustomLEDVerC.setText(QtGui.QApplication.translate("MainWindow", "LED Board C - dual LED", None, QtGui.QApplication.UnicodeUTF8))

