# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(682, 389)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.transmissionGroupBox = QtWidgets.QGroupBox(self.frame)
        self.transmissionGroupBox.setObjectName("transmissionGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.transmissionGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.transmissionTextEdit = QtWidgets.QTextEdit(self.transmissionGroupBox)
        self.transmissionTextEdit.setReadOnly(True)
        self.transmissionTextEdit.setObjectName("transmissionTextEdit")
        self.verticalLayout.addWidget(self.transmissionTextEdit)
        self.verticalLayout_2.addWidget(self.transmissionGroupBox)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.absorbanceGroupBox = QtWidgets.QGroupBox(self.frame_2)
        self.absorbanceGroupBox.setObjectName("absorbanceGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.absorbanceGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.absorbanceTextEdit = QtWidgets.QTextEdit(self.absorbanceGroupBox)
        self.absorbanceTextEdit.setReadOnly(True)
        self.absorbanceTextEdit.setObjectName("absorbanceTextEdit")
        self.verticalLayout_3.addWidget(self.absorbanceTextEdit)
        self.verticalLayout_4.addWidget(self.absorbanceGroupBox)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.samplesLineEdit = QtWidgets.QLineEdit(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.samplesLineEdit.sizePolicy().hasHeightForWidth())
        self.samplesLineEdit.setSizePolicy(sizePolicy)
        self.samplesLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.samplesLineEdit.setObjectName("samplesLineEdit")
        self.horizontalLayout_5.addWidget(self.samplesLineEdit)
        spacerItem = QtWidgets.QSpacerItem(143, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.LEDLabel = QtWidgets.QLabel(self.widget_5)
        self.LEDLabel.setObjectName("LEDLabel")
        self.horizontalLayout_5.addWidget(self.LEDLabel)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.LED0CheckBox = QtWidgets.QCheckBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED0CheckBox.sizePolicy().hasHeightForWidth())
        self.LED0CheckBox.setSizePolicy(sizePolicy)
        self.LED0CheckBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.LED0CheckBox.setChecked(True)
        self.LED0CheckBox.setObjectName("LED0CheckBox")
        self.horizontalLayout_5.addWidget(self.LED0CheckBox)
        self.LED1CheckBox = QtWidgets.QCheckBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED1CheckBox.sizePolicy().hasHeightForWidth())
        self.LED1CheckBox.setSizePolicy(sizePolicy)
        self.LED1CheckBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.LED1CheckBox.setChecked(True)
        self.LED1CheckBox.setObjectName("LED1CheckBox")
        self.horizontalLayout_5.addWidget(self.LED1CheckBox)
        self.LED2CheckBox = QtWidgets.QCheckBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED2CheckBox.sizePolicy().hasHeightForWidth())
        self.LED2CheckBox.setSizePolicy(sizePolicy)
        self.LED2CheckBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.LED2CheckBox.setChecked(True)
        self.LED2CheckBox.setObjectName("LED2CheckBox")
        self.horizontalLayout_5.addWidget(self.LED2CheckBox)
        self.LED3CheckBox = QtWidgets.QCheckBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LED3CheckBox.sizePolicy().hasHeightForWidth())
        self.LED3CheckBox.setSizePolicy(sizePolicy)
        self.LED3CheckBox.setMaximumSize(QtCore.QSize(65, 16777215))
        self.LED3CheckBox.setChecked(True)
        self.LED3CheckBox.setObjectName("LED3CheckBox")
        self.horizontalLayout_5.addWidget(self.LED3CheckBox)
        self.verticalLayout_5.addWidget(self.widget_5)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.portLineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLineEdit.sizePolicy().hasHeightForWidth())
        self.portLineEdit.setSizePolicy(sizePolicy)
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout.addWidget(self.portLineEdit)
        self.connectPushButton = QtWidgets.QPushButton(self.widget)
        self.connectPushButton.setObjectName("connectPushButton")
        self.horizontalLayout.addWidget(self.connectPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(322, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.calibratePushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibratePushButton.sizePolicy().hasHeightForWidth())
        self.calibratePushButton.setSizePolicy(sizePolicy)
        self.calibratePushButton.setObjectName("calibratePushButton")
        self.horizontalLayout.addWidget(self.calibratePushButton)
        self.measurePushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measurePushButton.sizePolicy().hasHeightForWidth())
        self.measurePushButton.setSizePolicy(sizePolicy)
        self.measurePushButton.setObjectName("measurePushButton")
        self.horizontalLayout.addWidget(self.measurePushButton)
        self.plotCheckBox = QtWidgets.QCheckBox(self.widget)
        self.plotCheckBox.setObjectName("plotCheckBox")
        self.horizontalLayout.addWidget(self.plotCheckBox)
        self.verticalLayout_5.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        self.menu_Options = QtWidgets.QMenu(self.menubar)
        self.menu_Options.setObjectName("menu_Options")
        self.menuSignificantDigits = QtWidgets.QMenu(self.menu_Options)
        self.menuSignificantDigits.setObjectName("menuSignificantDigits")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionStandardRGBLED = QtWidgets.QAction(MainWindow)
        self.actionStandardRGBLED.setCheckable(True)
        self.actionStandardRGBLED.setObjectName("actionStandardRGBLED")
        self.actionCustomLEDVerB = QtWidgets.QAction(MainWindow)
        self.actionCustomLEDVerB.setCheckable(True)
        self.actionCustomLEDVerB.setObjectName("actionCustomLEDVerB")
        self.actionSignificantDigits1 = QtWidgets.QAction(MainWindow)
        self.actionSignificantDigits1.setCheckable(True)
        self.actionSignificantDigits1.setObjectName("actionSignificantDigits1")
        self.actionSignificantDigits2 = QtWidgets.QAction(MainWindow)
        self.actionSignificantDigits2.setCheckable(True)
        self.actionSignificantDigits2.setObjectName("actionSignificantDigits2")
        self.actionSignificantDigits3 = QtWidgets.QAction(MainWindow)
        self.actionSignificantDigits3.setCheckable(True)
        self.actionSignificantDigits3.setObjectName("actionSignificantDigits3")
        self.actionSignificantDigits4 = QtWidgets.QAction(MainWindow)
        self.actionSignificantDigits4.setCheckable(True)
        self.actionSignificantDigits4.setObjectName("actionSignificantDigits4")
        self.actionCustomLEDVerC = QtWidgets.QAction(MainWindow)
        self.actionCustomLEDVerC.setCheckable(True)
        self.actionCustomLEDVerC.setObjectName("actionCustomLEDVerC")
        self.menuFile.addAction(self.actionSave)
        self.menu_Help.addAction(self.actionAbout)
        self.menuMode.addAction(self.actionStandardRGBLED)
        self.menuMode.addAction(self.actionCustomLEDVerB)
        self.menuMode.addAction(self.actionCustomLEDVerC)
        self.menu_Options.addAction(self.menuSignificantDigits.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menu_Options.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Colorimeter Basic"))
        self.transmissionGroupBox.setTitle(_translate("MainWindow", "Transmittance"))
        self.absorbanceGroupBox.setTitle(_translate("MainWindow", "Absorbance"))
        self.label_2.setText(_translate("MainWindow", "Samples    "))
        self.LEDLabel.setText(_translate("MainWindow", "LEDs"))
        self.LED0CheckBox.setText(_translate("MainWindow", "LED0"))
        self.LED1CheckBox.setText(_translate("MainWindow", "LED1"))
        self.LED2CheckBox.setText(_translate("MainWindow", "LED2"))
        self.LED3CheckBox.setText(_translate("MainWindow", "LED3"))
        self.label.setText(_translate("MainWindow", "Serial Port"))
        self.connectPushButton.setText(_translate("MainWindow", "Connect"))
        self.calibratePushButton.setText(_translate("MainWindow", "Calibrate"))
        self.measurePushButton.setText(_translate("MainWindow", "Measure"))
        self.plotCheckBox.setText(_translate("MainWindow", "Plot   "))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menuMode.setTitle(_translate("MainWindow", "&Mode"))
        self.menu_Options.setTitle(_translate("MainWindow", "&Options"))
        self.menuSignificantDigits.setTitle(_translate("MainWindow", "Significant Digits"))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionStandardRGBLED.setText(_translate("MainWindow", "Standard RGB LED"))
        self.actionCustomLEDVerB.setText(_translate("MainWindow", "LED Board B - single LED"))
        self.actionSignificantDigits1.setText(_translate("MainWindow", "1"))
        self.actionSignificantDigits2.setText(_translate("MainWindow", "2"))
        self.actionSignificantDigits3.setText(_translate("MainWindow", "3"))
        self.actionSignificantDigits4.setText(_translate("MainWindow", "4"))
        self.actionCustomLEDVerC.setText(_translate("MainWindow", "LED Board C - dual LED"))

