# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startup_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_startupDialog(object):
    def setupUi(self, startupDialog):
        startupDialog.setObjectName("startupDialog")
        startupDialog.resize(442, 260)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(startupDialog.sizePolicy().hasHeightForWidth())
        startupDialog.setSizePolicy(sizePolicy)
        startupDialog.setMinimumSize(QtCore.QSize(442, 260))
        startupDialog.setMaximumSize(QtCore.QSize(442, 260))
        self.verticalLayout = QtWidgets.QVBoxLayout(startupDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(startupDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.basicPushButton = QtWidgets.QPushButton(self.groupBox)
        self.basicPushButton.setObjectName("basicPushButton")
        self.horizontalLayout.addWidget(self.basicPushButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.line = QtWidgets.QFrame(startupDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.groupBox_2 = QtWidgets.QGroupBox(startupDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.plotPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.plotPushButton.setObjectName("plotPushButton")
        self.horizontalLayout_2.addWidget(self.plotPushButton)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.line_2 = QtWidgets.QFrame(startupDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.groupBox_3 = QtWidgets.QGroupBox(startupDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.measurePushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.measurePushButton.setObjectName("measurePushButton")
        self.horizontalLayout_3.addWidget(self.measurePushButton)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(startupDialog)
        QtCore.QMetaObject.connectSlotsByName(startupDialog)

    def retranslateUi(self, startupDialog):
        _translate = QtCore.QCoreApplication.translate
        startupDialog.setWindowTitle(_translate("startupDialog", "IO Rodeo Colorimeter"))
        self.groupBox.setTitle(_translate("startupDialog", "Basic Program"))
        self.label.setText(_translate("startupDialog", "Measure transmittance and absorbance"))
        self.basicPushButton.setText(_translate("startupDialog", "Start"))
        self.groupBox_2.setTitle(_translate("startupDialog", "Plotting Program"))
        self.label_2.setText(_translate("startupDialog", "Generate standard curves and plot data"))
        self.plotPushButton.setText(_translate("startupDialog", "Start"))
        self.groupBox_3.setTitle(_translate("startupDialog", "Measurement Program"))
        self.label_3.setText(_translate("startupDialog", "Measure the concentration of solutions "))
        self.measurePushButton.setText(_translate("startupDialog", "Start"))

